### ISSUE TITLE
Fix encoding errors when dealing with PNG images

### ISSUE THREAD

**Issue by SapneshNaik** [SapneshNaik/GIT205-26May#15]
Vivamus suscipit tortor eget felis porttitor volutpat. Donec sollicitudin molestie malesuada. Nulla porttitor accumsan tincidunt. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Sed porttitor lectus nibh. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Nulla quis lorem ut libero malesuada feugiat. Donec rutrum congue leo eget malesuada. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Nulla porttitor accumsan tincidunt. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Pellentesque in ipsum id orci porta dapibus. Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Pellentesque in ipsum id orci porta dapibus. Curabitur aliquet quam id dui posuere blandit. Proin eget tortor risus. Nulla porttitor accumsan tincidunt. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.

Vivamus suscipit tortor eget felis porttitor volutpat. Donec sollicitudin molestie malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Sed porttitor lectus nibh. Donec sollicitudin molestie malesuada. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Proin eget tortor risus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eget tortor risus. Donec rutrum congue leo eget malesuada. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis lorem ut libero malesuada feugiat. Donec rutrum congue leo eget malesuada. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Donec sollicitudin molestie malesuada. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus.

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue has a bounty of $500.00 ready to be claimed!**

- If you are a Contributor and would like to complete this task to claim the bounty you can **Start Work** on the [GitCommits issue details page](https://sandbox.app.gitcommits.com/issue/fix-encoding-errors-when-dealing-with-png-images).
- If you would like to see this issue completed more quickly, please **Add Funding** to the bounty on the [GitCommits issue details page](https://sandbox.app.gitcommits.com/issue/fix-encoding-errors-when-dealing-with-png-images).
- More open bounties are available in the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)
- Questions? Review our [FAQ](https://www.gitcommits.com/faq)

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. Open 2. **Started**  3. Submitted 4. Done

<hr>

**Work has been started.**

**<a href='https://sandbox.app.gitcommits.com/profile/cont1'>cont1</a> has been approved to start work.**

<hr />

**Message:** Go ahead! Please complete the bounty within time


<a href='https://sandbox.app.gitcommits.com/issue/fix-encoding-errors-when-dealing-with-png-images'>Click Here to view more</a> on the GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/cont1'>cont1</a>, your submission has been rejected by <a href='https://sandbox.app.gitcommits.com/profile/funder11'>funder11</a>.**
<hr />

**Message:** Pull Request has been rejected.


<a href='https://sandbox.app.gitcommits.com/issue/fix-encoding-errors-when-dealing-with-png-images'>Click Here to view more</a> on the GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/cont1'>cont1</a> Work has been approved by <a href='https://sandbox.app.gitcommits.com/profile/funder11'>funder11</a>.**
<hr />

**Message:** Pull request has been approved, you will receive the payment shortly.


<a href='https://sandbox.app.gitcommits.com/issue/fix-encoding-errors-when-dealing-with-png-images'>Click Here to view more</a> on the GitCommits Bounty detail page.
